apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: jdessy
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: registry.dev.afsmtddso.com/jdessy-harborproject/db@sha256:c0fa8ff0edae6c7e8c7da2630ba71517b1b8805ebf1ed4f9a71d4a47d1768596
        ports:
        - containerPort: 5432
